### ISSUE TITLE
nanchuan'issue

### ISSUE THREAD

**Issue by nanchuan211** [Jasons-impart/Create-Dimensional-Relics#15]
1.RS无线终端无合成台功能，需要取出放置身上找合成台合成，建议添加合成升级，类似于背包里的合成升级
2.机械动力机器在同一区块或同一地区过多，声音消失bug，不完全消声，会偶尔有声音，如切换物品栏，脚步声（多人出现）

**Comment by CPearl0** [comment]
一个问题提一个issue.这个关了 我重新提一下
