### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Courageqhx** [Jasons-impart/Create-Dimensional-Relics#9]
1 关于资源获取，仅提供矿区和矿脉钻井但不提供加工程序和运转应力，需要玩家自发建设增加产线和能源供给提高效率。资源区矿物种类梯度解锁 铜锌矿/铁矿/金矿 分别对应5/15/25人 分别获得成就月球空间站/火星空间站/…空间站的建立 红石/青金石/钻石仅可通过商店兑换获取 分别对应各种农作物及成品兑换
基础合成序列农产品兑换原木/原石/闪长岩/安山岩等
中级合成序列农产品兑换铜锌/铁/金等原矿
高级合成序列农产品兑换红石/青金石/钻石等原矿
最高合成序列农产品兑换蓝图炮 蓝图桌 蓝图 传送石碑
特殊合成序列农产品(酿酒)  兑换 文明进度 (全服文明进度贡献榜) 兑换表单内奖品合成表全部禁止如传送石碑
2 关于区块加载，每人领取1/2/4个区块加载器根据不同个人游戏进度获取，分别对应到达地球/月球/半人马霜原星。
3 世界观设定，文明进度累计解锁其他维度的进入开发权限 具体数值例如100组葡萄酒/1000组…/10000组 
分别对应例如 下届/天境/末地 可全服累计或战队累计。
4 工业公共设施 提供铁路站点 矿井 发射中心 交易市场 
但不提供铁轨 运行火车 应力 加工产线等需要玩家自主合作开发 
5 魔法设定 没玩过，但是可以考虑增加魔法艺术及前置与附属
https://www.mcmod.cn/class/2773.html
或植物魔法相关前置与附属
6 权限与传送 禁止tpa传送 和传送石碑等 提高随意传送和跨纬度传送的使用代价(提高交通建设的重要性和飞机等通勤设施的有效使用率)合理增加真实性
提高蓝图炮蓝图桌与蓝图的获取难度，可从商店兑换但不可合成，减少大批量机器复制出现增加服务器压力。蓝图相关转变为一次性，放置之后破坏无掉落，增加兑换频率。
7 想到再加，下课了o.0收拾东西回去玩游戏

**Comment by JasonQ1123** [comment]
提议1的话我觉得可以接受，但是可能会改成跟村民交易的形式；
提议2可以接受，但是目前还有个计划是删掉区块加载器然后改成ftb加载
提议3的有点过于折磨人了，不是非常接受
提议4可以在服务器试装
提议5的话目前还没想好装什么魔法
提议6接受但是蓝图大炮目前没有禁止的打算

**Comment by Fish-LP** [comment]
在readme文件添加mod列表与剧情

**Comment by Fish-LP** [comment]
为整合包添加最终物品作为游戏目标。

**Comment by Fish-LP** [comment]
在世界中添加作者标志物的生成

**Comment by Fish-LP** [comment]
![Screenshot_2024-03-30-11-32-31-85_149003a2d400f6adb210d7e357a3a646](https://github.com/Jasons-impart/Create-Dimensional-Relics/assets/129402160/d82a39a0-5dd5-4693-bec0-195df15e58eb)
保护猫猫，将猫的掉落物改为下届合金碎片

**Comment by JasonQ1123** [comment]
> ![Screenshot_2024-03-30-11-32-31-85_149003a2d400f6adb210d7e357a3a646](https://github.com/Jasons-impart/Create-Dimensional-Relics/assets/129402160/d82a39a0-5dd5-4693-bec0-195df15e58eb)
> 保护猫猫，将猫的掉落物改为下届合金碎片

阿这...

**Comment by JasonQ1123** [comment]
> 为整合包添加最终物品作为游戏目标。

太过遥远

**Comment by CPearl0** [comment]
一个建议提一个issue，这个就先关了
